version: 1.0.{build}
image: Ubuntu1804

environment:
  matrix:
    - image: ubuntu:1604
      runtime: docker
    - image: ubuntu:1804
      runtime: docker
    - image: debian:9
      runtime: docker
    - image: fedora:30
      runtime: docker
    - image: centos:7
      runtime: docker
  GOPATH: /usr/go/
  GO111MODULES: on

build_script:
  - sh: sudo snap install go --classic
  - sh: sudo ./build.sh ${image} ${runtime}

artifacts:
  - path: images/*
    type: File

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: iO9qBR19uG7zvP2ocrkrn35YTchFxm0G0stLeZ/AVeY3RAIXoUt5Q1H9nGiCN6Ao
  artifact: /.*/
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
