version: 1.0.{build}
image: Ubuntu1804

init:
  - sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

environment:
  APPVEYOR_SSH_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDF4fzNRtQoSJMmp+kgg+K+zGAJu9YKpYSH/96nkIBXbXqZpOmtGnweFTXLcJQHV46YZCCQdcFxjm6e2vUG+6F4e3aGuCQBgiHMcB0/Qsvm2f84bHQpUfxsK5Sa/1wDEe8pyWXuylTbiW1jV+knH3m3b7uijBh4qaHBF8hIqHSOtP5X67NTBcFYuQ8gkiqM519BOxYq/K+A5vFDA62vdErpdjrZbw8A7+VXxzIkDRnztQNo5kVj2+/6UqaGzbSS4pvLszKOlvwB6g9vTAYcdP43NxgzOS42FnMclJfBm+IE6RhdWq8ulyvS5RdahzwEwQOBkxUnkiO4XWQXsaKbhcVl
  matrix:
    - image: ubuntu:1804
      config: capv
    - image: centos:7
      config: capv
    - image: ubuntu:1804
      config: docker
    - image: debian:9
      config: docker
    - image: fedora:30
      config: docker
    - image: centos:7
      config: docker
    - image: ubuntu:1804
      config: containerd
    - image: centos:7
      config: containerd

  GOPATH: /usr/go/
  GO111MODULES: on

build_script:
  - sh: sudo snap install go --classic
  - sh: sudo ./build.sh ${image} ${config}

artifacts:
  - path: images/*
    type: File

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: iO9qBR19uG7zvP2ocrkrn35YTchFxm0G0stLeZ/AVeY3RAIXoUt5Q1H9nGiCN6Ao
  artifact: /.*/
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
